import Header from '@/cmponents/partials/layout/Header'

import './global.scss'
import '../cmponents/styles/Layout.scss'
import '../cmponents/styles/Products.scss'
import '../cmponents/styles/Layout.scss'
import '../cmponents/styles/Navigation.scss'
import '../cmponents/styles/ProductPage.scss'
import '../cmponents/styles/Cart.scss'
import '../cmponents/styles/Admin.scss'

import type { Metadata } from 'next'
import Footer from '@/cmponents/partials/layout/Footer'
import Aside from '@/cmponents/partials/layout/Aside'
import { Providers } from '@/redux/Provider'

export const metadata: Metadata = {
  title: 'Catalog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
            <main>
              <Aside />
              {children}
            </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
